version: '3'
services:
    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      networks: 
        - desenv-local
      ports:
        - "5672:5672"
        - "15672:15672"
    redis:
        image: redis
        container_name: redis
        networks: 
            - desenv-local
    app1:
        build:
            context: .
            dockerfile: ./api-leaderboards.dockerfile
            args:
                JAR_FILE: ./target/leaderboards-api.jar
        image: luksrn/leaderboards
        container_name: leaderboards-app1
        ports:
            - "8080:8080"
        networks: 
            - desenv-local
        depends_on:
            - "redis"
            - "rabbitmq"
networks: 
    desenv-local:
        driver: bridge    

